apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serving-core-v0_24_0.yaml
- net-istio-v0_24_0.yaml
# - eventing-core-v0_22_0.yaml # Eventing is optional
- https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.5.0/components.yaml # metrics server (needed for HPA)
- allow-all-ns-knative-authorization-policy.yaml
- peerauthentication.yaml
# - monitoring/

patchesStrategicMerge:
# patches
- patches/config-istio.yaml
- patches/config-logging.yaml
- patches/config-network.yaml
- patches/config-observability.yaml
- patches/domain-config.yaml
- patches/increase-deadline.yaml
- patches/enable-istio-injection.yaml
- patches/enable-sidecar-istio-controller.yaml

# removals
- removals/remove-knative-ingress-gateway.yaml
- removals/remove-knative-local-gateway.yaml




images:
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  digest: sha256:624ad8df549de9192e7b0d2f596c08c5996f678b25ff94688464412890126bb1
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  digest: sha256:6b77fce9159173ce700cbe8202eb0ab33b2128688baadf34e916b7341889bde0
- name: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping
  digest: sha256:5f9d8293f8d8d04cbfeed796ea15cf6dd967d2213f326debfe76983ab58b63fd
- name: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping-webhook
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping-webhook
  digest: sha256:51800b3435af2cd551f7de5119133de3cb30e3d72ec9df18d5e2e14ec482668f
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  digest: sha256:881a707c3f5b8537adf1fd460405fb8e65ae2676e4591926f9cdfb4454efd350
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  digest: sha256:ff1e9ff5abfaf305bf9160177739dca00cffd0324e8dc718f6c0525910c9ecb0
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  digest: sha256:7f17fb47568a74de3f82bb512422a174017b7c06643a330557bc3445c8869932
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  digest: sha256:75d502bdff93e9c0e4611c2747d868b8d471f8d3a0402394de76ec2d98b89ce3
- name: k8s.gcr.io/metrics-server/metrics-server
  newName: k8s.gcr.io/metrics-server/metrics-server
  newTag: v0.5.0
